dist: trusty
sudo: required
services:
- docker
language: go
go:
  - "1.11.x"

env:
  - PGVERSION=latest
  - PGVERSION=10
  - PGVERSION=9
  - PGVERSION=8.4

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor

script:
- make test
- make vendor-status
- make vet
- make website-test
- source tests/env.sh
- docker-compose -f tests/docker-compose.yml ps
- docker-compose -f tests/docker-compose.yml up -d
- tests/wait-postgres-docker.sh tests/docker-compose.yml
- make testacc

branches:
  only:
  - tmp
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
